### ISSUE TITLE
Email a whole group with password reset link

### ISSUE THREAD

**Issue by migswd** [victor-in/Craft-Mailer#8]
I am importing 4000 frontend users in a group and as it is not possible to insert the password I have to send them all an email with the link to reset their password...
Is it posible with your plugin ?

**Comment by victor-in** [comment]
There are two ways to accomplish this:

**1.** [Set the '''passwordResetRequired''' field for each user to '''true'''](https://straightupcraft.com/articles/how-do-i-force-all-users-to-reset-their-password-in-craft-cms), then send them a mass mail, which links to your normal login-page. When they try to login, they'll be forced to reset their password.

**2.** Use the "Require Email Verification" option while creating a User. This will send them an email automatically. [See here](http://craftcms.stackexchange.com/a/82).

**3.** Use the [sendPasswordResetEmail() function](http://buildwithcraft.com/classreference/services/UsersService#sendPasswordResetEmail-detail), and loop once through all users.

I recommend you go with the third option, in case something goes wrong with your import. You don't want to send your users multiple reset mails.
